#!/bin/bash

if [ -z "$1" ]; then
	echo "Usage: lxc-ssh <host>"
	exit 0
fi

IP=$(lxc list | grep "$1" | grep 'RUNNING' | sed -E 's/.+ ([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}) .+/\1/')

if [ ! -z "$IP" ]; then
	ssh -l root $IP
fi
